### ISSUE TITLE
UDP listener: unexpected address type

### ISSUE THREAD

**Issue by yoursunny** [go-ndn/nfd#1]
Steps to reproduce:
1. modify `nfd.json`, set Listen[].Network to "udp"
2. run `nfd` with modified `nfd.json`

Expected: go-nfd listens on UDP port 6363
Actual: go-nfd terminates with `[core] listen udp :6363: unexpected address type :6363`

**Comment by taylorchu** [comment]
go-ndn will eventually support udp. It is not urgent.

**Comment by taylorchu** [comment]
Now the go-ndn client should support packet-oriented connection, but I will do the rest this weekend.

https://github.com/go-ndn/tlv/commit/cede9a1011cad336da24f43e6504c8aba1ce1e47

**Comment by taylorchu** [comment]
go-ndn/packet is created for this.
