### ISSUE TITLE
/localhost/nfd/rib/list: incorrect response Name

### ISSUE THREAD

**Issue by yoursunny** [go-ndn/nfd#2]
Steps to reproduce:
1. start go-nfd, listening on TCP port 6363
2. modify `$HOME/.ndn/client.conf` with: `transport=tcp://127.0.0.1:6363` so that ndn-cxx apps can connect to TCP :6363
3. execute `nfd-status -r`

Expected: zero or more routes appears
Actual: `ERROR: Name component does not have the requested marker or the value is not a nonNegativeInteger`

`ndn-tlv-peek /localhost/nfd/rib/list | tlvdump` reveals that the response Data Name is `ndn:/localhost/nfd/rib/list`.
A response Name from NFD is: `ndn:/localhost/nfd/rib/list/%FD%00%00%01M%1B%D5%B1%E7/%00%00`.
go-nfd is missing version and segment components.

**Comment by taylorchu** [comment]
8e46083

**Comment by taylorchu** [comment]
nfd-status has a bug in segment assembler where the data life time is set to 0.
